# -*- coding: utf-8 -*-
"""seminario_COLAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Upls2ADBT56eJOo0saDpWYGbnElThzTp

# Cisalhamento Antiplano em Célula Compósita com Inclusão — Equipe 3

**Métodos Numéricos para EDP · Mestrado em Modelagem Computacional (UFF/EEIMVR)**

> 🟢 **Este notebook roda 100% no Google Colab, do zero.** Ele cria os próprios
> módulos de código, não precisa de nenhum arquivo externo. Basta
> **Ambiente de execução → Executar tudo** (*Runtime → Run all*).

Resolvemos **o mesmo problema físico por três métodos** e os comparamos:

| Método | O que é |
|---|---|
| **MDF** — Diferenças Finitas | malha de pontos; derivadas viram diferenças entre vizinhos; resolve um sistema linear |
| **MEF** — Elementos Finitos | domínio dividido em elementos Q4; forma fraca (integral); resolve um sistema linear |
| **PINN** — Physics-Informed Neural Network | uma rede neural aproxima `w(x,y)` minimizando o resíduo da própria EDP |

O Colab já vem com `numpy`, `scipy`, `matplotlib` e `torch`. A PINN é **treinada
aqui dentro** (CPU já funciona; se quiser, ative GPU em *Ambiente de execução →
Alterar o tipo de ambiente de execução → GPU* para acelerar).

## 0. Criar os módulos do projeto

As células abaixo escrevem o código-fonte (idêntico ao do repositório) num pacote
`src/` dentro do ambiente do Colab. **Rode-as uma vez**; depois os `import` funcionam.
"""

import os
os.makedirs('src', exist_ok=True)
open('src/__init__.py', 'w').close()
print('pacote src/ criado')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/geometry.py
# """Geometria da celula representativa: dominio, inclusao e campo de modulo G(x,y).
# 
# Problema 3 (Equipe 3) - cisalhamento antiplano em celula compósita com inclusao
# quadrada central. Tudo aqui e puramente geometrico/material; os solvers consomem
# estas funcoes para montar seus sistemas.
# """
# 
# from dataclasses import dataclass
# 
# import numpy as np
# 
# 
# @dataclass(frozen=True)
# class Case:
#     """Parametros de um caso do problema.
# 
#     L  : lado da celula quadrada [0,L]x[0,L]
#     a  : "semi-lado" da inclusao quadrada central (lado = 2a); para o caso circular
#          de validacao, a e o raio da inclusao circular.
#     Gm : modulo de cisalhamento da matriz
#     Gi : modulo de cisalhamento da inclusao
#     gamma : deformacao de cisalhamento macroscopica imposta (w(L,y) = gamma*L)
#     shape : "square" (caso oficial) ou "circle" (validacao analitica)
#     """
# 
#     L: float = 1.0
#     a: float = 0.15
#     Gm: float = 1.0
#     Gi: float = 5.0
#     gamma: float = 0.01
#     shape: str = "square"
# 
#     @property
#     def center(self):
#         """Centro do dominio (e da inclusao)."""
#         return (self.L / 2.0, self.L / 2.0)
# 
# 
# # Caso oficial (secao 1 do CLAUDE.md)
# OFFICIAL = Case(L=1.0, a=0.15, Gm=1.0, Gi=5.0, gamma=0.01, shape="square")
# # Caso de validacao analitica com inclusao circular (secao 2)
# VALIDATION = Case(L=1.0, a=0.15, Gm=1.0, Gi=10.0, gamma=0.01, shape="circle")
# 
# 
# def inclusion_mask(x, y, case: Case):
#     """Mascara booleana: True onde (x,y) esta DENTRO da inclusao.
# 
#     Aceita arrays (broadcast) ou escalares. Para a inclusao quadrada usa a
#     norma do infinito (quadrado alinhado aos eixos); para a circular, a norma 2.
#     """
#     x = np.asarray(x, dtype=float)
#     y = np.asarray(y, dtype=float)
#     cx, cy = case.center
#     dx = x - cx
#     dy = y - cy
#     if case.shape == "square":
#         return (np.abs(dx) <= case.a) & (np.abs(dy) <= case.a)
#     elif case.shape == "circle":
#         return (dx * dx + dy * dy) <= case.a * case.a
#     raise ValueError(f"shape desconhecido: {case.shape!r}")
# 
# 
# def G_field(x, y, case: Case):
#     """Campo material G(x,y): Gi dentro da inclusao, Gm fora. Vetorizado."""
#     inside = inclusion_mask(x, y, case)
#     return np.where(inside, case.Gi, case.Gm)
# 
# 
# def grid(N, case: Case):
#     """Malha regular (N+1)x(N+1) sobre [0,L]^2.
# 
#     Retorna (X, Y, x1d, h) com X,Y no formato 'ij' (X[i,j], Y[i,j]) de modo que
#     o indice i anda em x e j anda em y -- convencao usada pelo solver MDF.
#     """
#     x1d = np.linspace(0.0, case.L, N + 1)
#     X, Y = np.meshgrid(x1d, x1d, indexing="ij")
#     h = case.L / N
#     return X, Y, x1d, h
# 
# 
# def inclusion_outline(case: Case, n=200):
#     """Pontos (xs, ys) do contorno da inclusao, para sobrepor nas figuras."""
#     cx, cy = case.center
#     if case.shape == "square":
#         a = case.a
#         xs = [cx - a, cx + a, cx + a, cx - a, cx - a]
#         ys = [cy - a, cy - a, cy + a, cy + a, cy - a]
#         return np.array(xs), np.array(ys)
#     else:
#         t = np.linspace(0, 2 * np.pi, n)
#         return cx + case.a * np.cos(t), cy + case.a * np.sin(t)
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/analytic.py
# """Solucao analitica do cisalhamento antiplano para INCLUSAO CIRCULAR.
# 
# Usada apenas para validacao (secao 2 do CLAUDE.md). O caso quadrado oficial nao
# tem solucao fechada; por isso validamos cada solver contra esta solucao circular
# classica (inclusao circular de raio a em matriz com deformacao remota w_inf = gamma*x),
# avaliada longe das bordas (a teoria supoe matriz infinita).
# 
# Coordenadas polares com origem no CENTRO da inclusao (= centro do dominio):
#     Dentro (r < a):  wi = [ 2 Gm / (Gi + Gm) ] * gamma * r * cos(theta)
#     Fora   (r > a):  wm = gamma*r*cos(theta) + gamma*a^2*(Gm-Gi)/(Gm+Gi)*cos(theta)/r
# 
# Para que a BC remota gamma*x case com o dominio finito [0,L]^2 (onde impomos
# w(0,y)=0 e w(L,y)=gamma*L), trabalhamos com o deslocamento relativo ao centro e
# somamos o offset gamma*cx, de modo que a solucao analitica tambem satisfaca
# w(0,y) ~ 0 e w(L,y) ~ gamma*L longe da inclusao.
# """
# 
# import numpy as np
# 
# from .geometry import Case
# 
# 
# def w_analytic(x, y, case: Case):
#     """Deslocamento w(x,y) da solucao circular analitica.
# 
#     O campo base e gamma*x (deformacao remota). A inclusao perturba esse campo.
#     Retorna array com a mesma forma de x,y.
#     """
#     if case.shape != "circle":
#         raise ValueError("w_analytic so vale para o caso de inclusao circular.")
# 
#     x = np.asarray(x, dtype=float)
#     y = np.asarray(y, dtype=float)
#     cx, cy = case.center
#     dx = x - cx
#     dy = y - cy
#     r = np.hypot(dx, dy)
#     a, Gm, Gi, g = case.a, case.Gm, case.Gi, case.gamma
# 
#     # Evita divisao por zero no centro (r=0 cai no ramo interno, onde w=0 mesmo).
#     r_safe = np.where(r == 0.0, 1.0, r)
#     cos_t = dx / r_safe  # = cos(theta); em r=0 o valor e irrelevante (ramo interno)
# 
#     inside = r < a
#     # Componente relativa ao centro
#     w_in = (2.0 * Gm / (Gi + Gm)) * g * r * cos_t
#     w_out = g * r * cos_t + g * a * a * (Gm - Gi) / (Gm + Gi) * cos_t / r_safe
#     w_rel = np.where(inside, w_in, w_out)
# 
#     # Offset para alinhar com a BC do dominio finito: w = gamma*x no campo remoto.
#     # w_rel ja contem gamma*dx; somamos gamma*cx para recuperar gamma*x.
#     return w_rel + g * cx
# 
# 
# def tau_analytic(x, y, case: Case):
#     """Tensoes (tau_xz, tau_yz) = G * grad(w) da solucao circular analitica.
# 
#     Calculadas por diferenciacao analitica do campo acima. Retorna (txz, tyz).
#     """
#     if case.shape != "circle":
#         raise ValueError("tau_analytic so vale para o caso de inclusao circular.")
# 
#     x = np.asarray(x, dtype=float)
#     y = np.asarray(y, dtype=float)
#     cx, cy = case.center
#     dx = x - cx
#     dy = y - cy
#     r2 = dx * dx + dy * dy
#     a, Gm, Gi, g = case.a, case.Gm, case.Gi, case.gamma
# 
#     r2_safe = np.where(r2 == 0.0, 1.0, r2)
#     inside = r2 < a * a
# 
#     # Dentro: w = C*gamma*dx com C = 2Gm/(Gi+Gm)  => grad = (C*gamma, 0), G = Gi
#     C = 2.0 * Gm / (Gi + Gm)
#     dwdx_in = C * g
#     dwdy_in = np.zeros_like(dx)
# 
#     # Fora: w = gamma*dx + B*dx/r^2 com B = gamma*a^2*(Gm-Gi)/(Gm+Gi)
#     #   d/dx [dx/r^2] = (r^2 - 2 dx^2)/r^4 = (dy^2 - dx^2)/r^4
#     #   d/dy [dx/r^2] = -2 dx dy / r^4
#     B = g * a * a * (Gm - Gi) / (Gm + Gi)
#     dwdx_out = g + B * (dy * dy - dx * dx) / (r2_safe * r2_safe)
#     dwdy_out = B * (-2.0 * dx * dy) / (r2_safe * r2_safe)
# 
#     dwdx = np.where(inside, dwdx_in, dwdx_out)
#     dwdy = np.where(inside, dwdy_in, dwdy_out)
#     G = np.where(inside, Gi, Gm)
#     return G * dwdx, G * dwdy
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/fdm.py
# """Solver por Metodo de Diferencas Finitas (MDF) para -div(G grad w) = 0.
# 
# Discretizacao CONSERVATIVA (forma de fluxo) numa malha regular (N+1)x(N+1):
# 
#   -(1/h^2)[ G_{i+1/2,j}(w_{i+1,j}-w_{i,j}) - G_{i-1/2,j}(w_{i,j}-w_{i-1,j})
#           + G_{i,j+1/2}(w_{i,j+1}-w_{i,j}) - G_{i,j-1/2}(w_{i,j}-w_{i,j-1}) ] = 0
# 
# As condutividades nas FACES usam MEDIA HARMONICA dos G nodais vizinhos -- esse e o
# ponto fisico central: trata corretamente o salto de G na interface matriz/inclusao
# (continuidade do fluxo normal). BCs:
#   - Dirichlet nas laterais (x=0 e x=L): linha identidade no sistema.
#   - Neumann homogeneo no topo/base (y=0 e y=L): nos-fantasma por reflexao.
# 
# Stack: numpy + scipy apenas.
# """
# 
# import numpy as np
# import scipy.sparse as sp
# from scipy.sparse.linalg import spsolve
# 
# from .geometry import Case, G_field, grid
# 
# 
# def _harmonic(a, b):
#     """Media harmonica elemento a elemento (faces). Evita divisao por zero."""
#     s = a + b
#     s = np.where(s == 0.0, 1.0, s)
#     return 2.0 * a * b / s
# 
# 
# def solve_fdm(case: Case, N=80):
#     """Resolve o problema por MDF.
# 
#     Retorna dict com X, Y (malha 'ij'), W (deslocamento), txz, tyz, Gef, h, N, case.
#     """
#     X, Y, x1d, h = grid(N, case)
#     n = N + 1
#     Gnod = G_field(X, Y, case)  # G nos nos, shape (n, n) indexado [i, j]
# 
#     # Condutividades nas faces (media harmonica entre nos adjacentes).
#     # Gx[i,j] = G na face entre (i,j) e (i+1,j), i = 0..N-1
#     Gx = _harmonic(Gnod[:-1, :], Gnod[1:, :])      # shape (N, n)
#     # Gy[i,j] = G na face entre (i,j) e (i,j+1), j = 0..N-1
#     Gy = _harmonic(Gnod[:, :-1], Gnod[:, 1:])      # shape (n, N)
# 
#     def idx(i, j):
#         return i * n + j
# 
#     ndof = n * n
#     A = sp.lil_matrix((ndof, ndof))
#     b = np.zeros(ndof)
#     inv_h2 = 1.0 / (h * h)
# 
#     for i in range(n):
#         for j in range(n):
#             k = idx(i, j)
# 
#             # --- Dirichlet nas laterais esquerda/direita (x = 0, x = L) ---
#             if i == 0:
#                 A[k, k] = 1.0
#                 b[k] = 0.0                 # w(0, y) = 0
#                 continue
#             if i == N:
#                 A[k, k] = 1.0
#                 b[k] = case.gamma * case.L  # w(L, y) = gamma*L
#                 continue
# 
#             # Coeficientes das faces. Para j nas bordas (topo/base), Neumann
#             # homogeneo via no-fantasma: a face que sairia do dominio tem
#             # contribuicao nula (fluxo nulo), o que equivale a remover o termo.
#             cw = Gx[i - 1, j] * inv_h2     # face oeste  (i-1/2, j)
#             ce = Gx[i, j] * inv_h2         # face leste  (i+1/2, j)
#             cs = Gy[i, j - 1] * inv_h2 if j > 0 else 0.0   # face sul (i, j-1/2)
#             cn = Gy[i, j] * inv_h2 if j < N else 0.0       # face norte (i, j+1/2)
# 
#             diag = cw + ce + cs + cn
#             A[k, k] = diag
#             A[k, idx(i - 1, j)] = -cw
#             A[k, idx(i + 1, j)] = -ce
#             if j > 0:
#                 A[k, idx(i, j - 1)] = -cs
#             if j < N:
#                 A[k, idx(i, j + 1)] = -cn
#             # b[k] = 0 (sem fonte)
# 
#     W = spsolve(A.tocsr(), b).reshape(n, n)
# 
#     txz, tyz = _stresses(W, Gnod, h)
#     Gef = float(np.mean(txz) / case.gamma)
# 
#     return dict(X=X, Y=Y, W=W, txz=txz, tyz=tyz, Gef=Gef, h=h, N=N, case=case)
# 
# 
# def _stresses(W, Gnod, h):
#     """tau_xz = G dw/dx, tau_yz = G dw/dy por diferencas centrais (np.gradient)."""
#     dwdx = np.gradient(W, h, axis=0)
#     dwdy = np.gradient(W, h, axis=1)
#     return Gnod * dwdx, Gnod * dwdy
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/fem.py
# """Solver por Metodo de Elementos Finitos (MEF) para -div(G grad w) = 0.
# 
# Forma fraca: achar w tal que  int_Omega G grad(w).grad(v) dOmega = 0  para todo v
# admissivel. Malha estruturada de elementos quadrilaterais Q4 (bilineares), G
# atribuido por elemento (testando o centroide: dentro/fora da inclusao). Quadratura
# de Gauss 2x2.
# 
# BCs:
#   - Neumann homogeneo (topo/base) e condicao NATURAL -> nenhum termo extra.
#   - Dirichlet (laterais x=0, x=L) por eliminacao/penalizacao de graus de liberdade.
# 
# MEF escrito na mao (transparencia > caixa-preta). Stack: numpy + scipy.
# """
# 
# import numpy as np
# import scipy.sparse as sp
# from scipy.sparse.linalg import spsolve
# 
# from .geometry import Case, grid, inclusion_mask
# 
# # Pontos e pesos de Gauss 2x2 no elemento de referencia [-1,1]^2
# _GP = 1.0 / np.sqrt(3.0)
# _GAUSS = [(-_GP, -_GP), (_GP, -_GP), (_GP, _GP), (-_GP, _GP)]
# 
# 
# def _shape(xi, eta):
#     """Funcoes de forma Q4 e suas derivadas em (xi, eta). Retorna (Nf, dN)."""
#     Nf = 0.25 * np.array([
#         (1 - xi) * (1 - eta),
#         (1 + xi) * (1 - eta),
#         (1 + xi) * (1 + eta),
#         (1 - xi) * (1 + eta),
#     ])
#     # dN/dxi e dN/deta
#     dN = 0.25 * np.array([
#         [-(1 - eta), (1 - eta), (1 + eta), -(1 + eta)],   # d/dxi
#         [-(1 - xi), -(1 + xi), (1 + xi), (1 - xi)],        # d/deta
#     ])
#     return Nf, dN
# 
# 
# def solve_fem(case: Case, N=80):
#     """Resolve por MEF Q4 numa malha NxN elementos / (N+1)x(N+1) nos.
# 
#     Retorna dict com X, Y (malha 'ij'), W, txz, tyz, Gef, h, N, case.
#     """
#     X, Y, x1d, h = grid(N, case)
#     n = N + 1
#     coords = np.column_stack([X.ravel(), Y.ravel()])  # no global k = i*n + j
# 
#     def node(i, j):
#         return i * n + j
# 
#     ndof = n * n
#     K = sp.lil_matrix((ndof, ndof))
# 
#     # G por elemento via centroide
#     for ei in range(N):
#         for ej in range(N):
#             # nos do elemento (sentido anti-horario): SW, SE, NE, NW
#             ns = [node(ei, ej), node(ei + 1, ej), node(ei + 1, ej + 1), node(ei, ej + 1)]
#             xe = coords[ns, 0]
#             ye = coords[ns, 1]
#             cxe, cye = xe.mean(), ye.mean()
#             Ge = case.Gi if inclusion_mask(cxe, cye, case) else case.Gm
# 
#             Ke = np.zeros((4, 4))
#             for (xi, eta) in _GAUSS:
#                 _, dN = _shape(xi, eta)
#                 # Jacobiano J = dN . [xe ye]
#                 J = dN @ np.column_stack([xe, ye])  # 2x2
#                 detJ = np.linalg.det(J)
#                 invJ = np.linalg.inv(J)
#                 dNxy = invJ @ dN  # derivadas em x,y, shape (2,4)
#                 Ke += Ge * (dNxy.T @ dNxy) * detJ  # peso de Gauss = 1
# 
#             for a in range(4):
#                 for b in range(4):
#                     K[ns[a], ns[b]] += Ke[a, b]
# 
#     K = K.tocsr()
#     F = np.zeros(ndof)
# 
#     # --- Dirichlet por eliminacao ---
#     # x=0 -> w=0 ; x=L -> w=gamma*L
#     fixed = {}
#     for j in range(n):
#         fixed[node(0, j)] = 0.0
#         fixed[node(N, j)] = case.gamma * case.L
# 
#     free = np.array([k for k in range(ndof) if k not in fixed], dtype=int)
#     fixed_idx = np.array(sorted(fixed.keys()), dtype=int)
#     fixed_val = np.array([fixed[k] for k in fixed_idx], dtype=float)
# 
#     # Move termos conhecidos para o RHS: F_free -= K[free, fixed] @ fixed_val
#     F_eff = F[free] - K[free][:, fixed_idx] @ fixed_val
#     K_ff = K[free][:, free]
# 
#     w = np.zeros(ndof)
#     w[fixed_idx] = fixed_val
#     w[free] = spsolve(K_ff, F_eff)
# 
#     W = w.reshape(n, n)
#     txz, tyz = _stresses_fem(W, X, Y, case, N, h)
#     Gef = float(np.mean(txz) / case.gamma)
# 
#     return dict(X=X, Y=Y, W=W, txz=txz, tyz=tyz, Gef=Gef, h=h, N=N, case=case)
# 
# 
# def _stresses_fem(W, X, Y, case, N, h):
#     """Tensoes nodais. Usa G nodal (consistente com a visualizacao) e gradiente
#     central de w; e a mesma convencao do MDF, o que torna a comparacao justa."""
#     from .geometry import G_field
#     Gnod = G_field(X, Y, case)
#     dwdx = np.gradient(W, h, axis=0)
#     dwdy = np.gradient(W, h, axis=1)
#     return Gnod * dwdx, Gnod * dwdy
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/metrics.py
# """Metricas de comparacao entre solucoes (secao 3 do CLAUDE.md)."""
# 
# import numpy as np
# 
# 
# def rel_l2(num, ref, mask=None):
#     """Erro relativo em norma L2:  ||num - ref||_2 / ||ref||_2.
# 
#     mask (booleano, opcional) restringe o calculo a uma regiao -- util para
#     excluir pontos colados na borda externa na validacao circular.
#     """
#     num = np.asarray(num, dtype=float)
#     ref = np.asarray(ref, dtype=float)
#     if mask is not None:
#         num = num[mask]
#         ref = ref[mask]
#     denom = np.linalg.norm(ref.ravel())
#     if denom == 0.0:
#         return float(np.linalg.norm((num - ref).ravel()))
#     return float(np.linalg.norm((num - ref).ravel()) / denom)
# 
# 
# def r2_score(pred, ref):
#     """Coeficiente de determinacao R^2 entre pred e ref (para scatter da PINN)."""
#     pred = np.asarray(pred, dtype=float).ravel()
#     ref = np.asarray(ref, dtype=float).ravel()
#     ss_res = np.sum((ref - pred) ** 2)
#     ss_tot = np.sum((ref - ref.mean()) ** 2)
#     if ss_tot == 0.0:
#         return 1.0 if ss_res == 0.0 else 0.0
#     return float(1.0 - ss_res / ss_tot)
# 
# 
# def effective_modulus(txz, gamma):
#     """Modulo de cisalhamento efetivo Gef = <tau_xz> / gamma."""
#     return float(np.mean(txz) / gamma)
# 
# 
# def field_errors(sol, ref, mask=None):
#     """Dicionario de erros relativos para w, txz, tyz entre duas solucoes (dicts
#     com chaves 'W','txz','tyz')."""
#     return {
#         "w": rel_l2(sol["W"], ref["W"], mask),
#         "txz": rel_l2(sol["txz"], ref["txz"], mask),
#         "tyz": rel_l2(sol["tyz"], ref["tyz"], mask),
#     }
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/viz.py
# """Todas as funcoes de visualizacao do projeto (secao 6 do CLAUDE.md).
# 
# Convencoes:
#   - Toda figura de campo sobrepoe o contorno da inclusao (`overlay_inclusion`).
#   - Saidas em outputs/figures/ com dpi>=150.
#   - Paleta consistente: 'viridis' para w, 'coolwarm'/'RdBu_r' para fluxos e diffs.
#   - As malhas seguem a convencao 'ij' (X[i,j], Y[i,j]); para pcolormesh/imshow
#     usamos .T para mapear (linhas=y, colunas=x) corretamente.
# """
# 
# import os
# 
# import matplotlib
# matplotlib.use("Agg")  # backend nao-interativo p/ salvar em scripts
# import matplotlib.pyplot as plt
# import numpy as np
# from mpl_toolkits.mplot3d import Axes3D  # noqa: F401  (registra projecao 3d)
# 
# from .geometry import Case, G_field, inclusion_outline, inclusion_mask
# 
# FIGDIR = os.path.join(os.path.dirname(__file__), "..", "outputs", "figures")
# W_CMAP = "viridis"
# TAU_CMAP = "coolwarm"
# DIFF_CMAP = "RdBu_r"
# METHOD_COLORS = {"MDF": "#1f77b4", "MEF": "#2ca02c", "PINN": "#d62728",
#                  "Analitico": "k", "Referencia": "k"}
# 
# 
# def _ensure_dir():
#     os.makedirs(FIGDIR, exist_ok=True)
# 
# 
# def _save(fig, name):
#     _ensure_dir()
#     path = os.path.join(FIGDIR, name)
#     fig.savefig(path, dpi=160, bbox_inches="tight")
#     return path
# 
# 
# def overlay_inclusion(ax, case: Case, color="k", lw=1.8, ls="-"):
#     """Desenha o contorno da inclusao sobre um eixo de campo."""
#     xs, ys = inclusion_outline(case)
#     ax.plot(xs, ys, color=color, lw=lw, ls=ls, zorder=5)
# 
# 
# # --------------------------------------------------------------------------
# # Geometria / setup (figuras 1-4)
# # --------------------------------------------------------------------------
# 
# def fig_material_map(case: Case, N=200, save="01_mapa_material.png"):
#     """Fig 1: heatmap discreto de G(x,y) (matriz vs inclusao)."""
#     x = np.linspace(0, case.L, N)
#     X, Y = np.meshgrid(x, x, indexing="ij")
#     G = G_field(X, Y, case)
#     fig, ax = plt.subplots(figsize=(5, 4.2))
#     pc = ax.pcolormesh(X, Y, G, cmap="YlOrRd", shading="auto")
#     overlay_inclusion(ax, case)
#     fig.colorbar(pc, ax=ax, label="G(x,y)")
#     ax.set_title(f"Mapa material  (Gm={case.Gm}, Gi={case.Gi})")
#     ax.set_xlabel("x"); ax.set_ylabel("y"); ax.set_aspect("equal")
#     return _save(fig, save), fig
# 
# 
# def fig_fdm_grid(case: Case, N=20, save="02_malha_mdf.png"):
#     """Fig 2: malha MDF com nos da inclusao destacados."""
#     x = np.linspace(0, case.L, N + 1)
#     X, Y = np.meshgrid(x, x, indexing="ij")
#     inside = inclusion_mask(X, Y, case)
#     fig, ax = plt.subplots(figsize=(5, 5))
#     ax.plot(X, Y, "o", color="0.7", ms=3)
#     ax.plot(X.T, Y.T, color="0.85", lw=0.5)
#     ax.plot(X, Y, color="0.85", lw=0.5)
#     ax.plot(X[inside], Y[inside], "o", color="#d62728", ms=4, label="nos na inclusao")
#     overlay_inclusion(ax, case)
#     ax.set_title(f"Malha MDF (N={N})"); ax.set_aspect("equal")
#     ax.set_xlabel("x"); ax.set_ylabel("y"); ax.legend(loc="upper left", fontsize=8)
#     return _save(fig, save), fig
# 
# 
# def fig_fem_mesh(case: Case, N=20, save="03_malha_mef.png"):
#     """Fig 3: malha MEF (elementos Q4) colorida por G do elemento."""
#     x = np.linspace(0, case.L, N + 1)
#     fig, ax = plt.subplots(figsize=(5, 5))
#     for ei in range(N):
#         for ej in range(N):
#             cx = 0.5 * (x[ei] + x[ei + 1])
#             cy = 0.5 * (x[ej] + x[ej + 1])
#             Ge = case.Gi if inclusion_mask(cx, cy, case) else case.Gm
#             color = "#fdbb84" if Ge == case.Gm else "#e34a33"
#             ax.add_patch(plt.Rectangle((x[ei], x[ej]), x[ei + 1] - x[ei],
#                                        x[ej + 1] - x[ej], facecolor=color,
#                                        edgecolor="0.8", lw=0.4))
#     overlay_inclusion(ax, case)
#     ax.set_xlim(0, case.L); ax.set_ylim(0, case.L); ax.set_aspect("equal")
#     ax.set_title(f"Malha MEF Q4 (N={N}) por G do elemento")
#     ax.set_xlabel("x"); ax.set_ylabel("y")
#     return _save(fig, save), fig
# 
# 
# def fig_pinn_points(pts: dict, case: Case, save="04_pontos_pinn.png"):
#     """Fig 4: distribuicao dos pontos de colocacao da PINN.
# 
#     pts: dict com chaves opcionais 'interior_m','interior_i','boundary','interface'
#     cada uma um array (n,2).
#     """
#     fig, ax = plt.subplots(figsize=(5.2, 5))
#     styles = {
#         "interior_m": ("matriz (EDP)", "#9ecae1", 4),
#         "interior_i": ("inclusao (EDP)", "#fdae6b", 4),
#         "boundary": ("contorno", "#31a354", 10),
#         "interface": ("interface", "#d62728", 12),
#     }
#     for key, (lab, col, ms) in styles.items():
#         P = pts.get(key)
#         if P is not None and len(P):
#             ax.scatter(P[:, 0], P[:, 1], s=ms, c=col, label=lab, alpha=0.7)
#     overlay_inclusion(ax, case)
#     ax.set_aspect("equal"); ax.set_xlim(0, case.L); ax.set_ylim(0, case.L)
#     ax.set_title("Pontos de colocacao da PINN")
#     ax.set_xlabel("x"); ax.set_ylabel("y"); ax.legend(fontsize=8, loc="upper right")
#     return _save(fig, save), fig
# 
# 
# # --------------------------------------------------------------------------
# # Campos de solucao (figuras 5-9)
# # --------------------------------------------------------------------------
# 
# def fig_field_heatmap(sol, field="W", case=None, save=None, title=None,
#                       cmap=None, vmin=None, vmax=None):
#     """Fig 5/8: heatmap de um campo (W, txz, tyz) com contorno da inclusao."""
#     case = case or sol["case"]
#     Z = sol[field]
#     cmap = cmap or (W_CMAP if field == "W" else TAU_CMAP)
#     fig, ax = plt.subplots(figsize=(5.2, 4.4))
#     pc = ax.pcolormesh(sol["X"], sol["Y"], Z, cmap=cmap, shading="auto",
#                        vmin=vmin, vmax=vmax)
#     overlay_inclusion(ax, case)
#     fig.colorbar(pc, ax=ax, label=field)
#     ax.set_title(title or field); ax.set_aspect("equal")
#     ax.set_xlabel("x"); ax.set_ylabel("y")
#     if save:
#         return _save(fig, save), fig
#     return None, fig
# 
# 
# def fig_surface(sol, case=None, save="06_superficie_w.png", title="w(x,y)"):
#     """Fig 6: superficie 3D de w(x,y)."""
#     case = case or sol["case"]
#     fig = plt.figure(figsize=(6, 4.6))
#     ax = fig.add_subplot(111, projection="3d")
#     ax.plot_surface(sol["X"], sol["Y"], sol["W"], cmap=W_CMAP,
#                     linewidth=0, antialiased=True)
#     ax.set_title(title); ax.set_xlabel("x"); ax.set_ylabel("y"); ax.set_zlabel("w")
#     return _save(fig, save), fig
# 
# 
# def fig_contour(sol, case=None, save="07_curvas_nivel_w.png", title="Curvas de nivel de w"):
#     """Fig 7: curvas de nivel de w."""
#     case = case or sol["case"]
#     fig, ax = plt.subplots(figsize=(5.2, 4.4))
#     cs = ax.contour(sol["X"], sol["Y"], sol["W"], levels=15, cmap=W_CMAP)
#     ax.clabel(cs, inline=True, fontsize=7)
#     overlay_inclusion(ax, case)
#     ax.set_title(title); ax.set_aspect("equal")
#     ax.set_xlabel("x"); ax.set_ylabel("y")
#     return _save(fig, save), fig
#
#
# def fig_field_contourf(sol, field="W", case=None, save=None, title=None,
#                        cmap=None, levels=18, vmin=None, vmax=None):
#     """Heatmap 'em curvas': bandas de cor (contourf) + isolinhas sobrepostas.
#
#     Mesma informacao de fig_field_heatmap, mas o campo aparece como curvas de
#     nivel preenchidas, destacando por onde o campo cresce/decai.
#     """
#     case = case or sol["case"]
#     Z = sol[field]
#     cmap = cmap or (W_CMAP if field == "W" else TAU_CMAP)
#     fig, ax = plt.subplots(figsize=(5.2, 4.4))
#     cf = ax.contourf(sol["X"], sol["Y"], Z, levels=levels, cmap=cmap,
#                      vmin=vmin, vmax=vmax)
#     ax.contour(sol["X"], sol["Y"], Z, levels=levels, colors="k",
#                linewidths=0.4, alpha=0.45)
#     overlay_inclusion(ax, case)
#     fig.colorbar(cf, ax=ax, label=field)
#     ax.set_title(title or field); ax.set_aspect("equal")
#     ax.set_xlabel("x"); ax.set_ylabel("y")
#     if save:
#         return _save(fig, save), fig
#     return None, fig
#
#
# def fig_flux_field(sol, case=None, save="09_fluxo.png", step=6, mode="quiver"):
#     """Fig 9: campo vetorial do fluxo (txz, tyz) -- quiver ou streamplot."""
#     case = case or sol["case"]
#     X, Y, U, V = sol["X"], sol["Y"], sol["txz"], sol["tyz"]
#     fig, ax = plt.subplots(figsize=(5.4, 4.6))
#     mag = np.hypot(U, V)
#     if mode == "stream":
#         # streamplot exige grade 1D crescente e ordem (y, x)
#         ax.streamplot(X[:, 0], Y[0, :], U.T, V.T, color=mag.T, cmap=TAU_CMAP, density=1.2)
#     else:
#         s = slice(None, None, step)
#         ax.quiver(X[s, s], Y[s, s], U[s, s], V[s, s], mag[s, s], cmap=TAU_CMAP)
#     overlay_inclusion(ax, case)
#     ax.set_title("Fluxo de cisalhamento (txz, tyz)"); ax.set_aspect("equal")
#     ax.set_xlabel("x"); ax.set_ylabel("y"); ax.set_xlim(0, case.L); ax.set_ylim(0, case.L)
#     return _save(fig, save), fig
# 
# 
# # --------------------------------------------------------------------------
# # Validacao circular (figuras 10-11)
# # --------------------------------------------------------------------------
# 
# def fig_centerline_validation(sol, w_ref_func, case=None,
#                               save="10_perfil_central.png"):
#     """Fig 10: perfil de w na linha horizontal central: numerico x analitico."""
#     case = case or sol["case"]
#     n = sol["W"].shape[1]
#     jmid = n // 2
#     x = sol["X"][:, jmid]
#     y = sol["Y"][:, jmid]
#     w_num = sol["W"][:, jmid]
#     w_ref = w_ref_func(x, y, case)
#     fig, ax = plt.subplots(figsize=(6, 4))
#     ax.plot(x, w_ref, "k-", lw=2, label="analitico")
#     ax.plot(x, w_num, "o", color="#1f77b4", ms=3, label="numerico")
#     ax.axvspan(case.center[0] - case.a, case.center[0] + case.a,
#                color="0.85", alpha=0.5, label="inclusao")
#     ax.set_xlabel("x"); ax.set_ylabel("w (linha central)")
#     ax.set_title("Validacao: perfil central"); ax.legend(fontsize=8)
#     return _save(fig, save), fig
# 
# 
# def fig_error_map(sol, w_ref_func, case=None, save="11_mapa_erro.png"):
#     """Fig 11: mapa de erro absoluto |w_num - w_analitico|."""
#     case = case or sol["case"]
#     Wref = w_ref_func(sol["X"], sol["Y"], case)
#     err = np.abs(sol["W"] - Wref)
#     fig, ax = plt.subplots(figsize=(5.2, 4.4))
#     pc = ax.pcolormesh(sol["X"], sol["Y"], err, cmap="magma", shading="auto")
#     overlay_inclusion(ax, case, color="w")
#     fig.colorbar(pc, ax=ax, label="|w_num - w_ref|")
#     ax.set_title("Erro absoluto (vs analitico)"); ax.set_aspect("equal")
#     ax.set_xlabel("x"); ax.set_ylabel("y")
#     return _save(fig, save), fig
# 
# 
# # --------------------------------------------------------------------------
# # PINN treino (figuras 12-13)
# # --------------------------------------------------------------------------
# 
# def fig_loss_history(history: dict, save="12_loss_pinn.png"):
#     """Fig 12: evolucao da loss (total e componentes) em escala log."""
#     fig, ax = plt.subplots(figsize=(6.4, 4.2))
#     for key, vals in history.items():
#         ax.semilogy(vals, label=key)
#     ax.set_xlabel("epoca"); ax.set_ylabel("loss (log)")
#     ax.set_title("Evolucao da loss da PINN"); ax.legend(fontsize=8); ax.grid(alpha=0.3)
#     return _save(fig, save), fig
# 
# 
# def fig_scatter_r2(w_pred, w_ref, save="13_scatter_r2.png", label="PINN"):
#     """Fig 13: scatter w_pred x w_ref com R^2 anotado."""
#     from .metrics import r2_score
#     w_pred = np.asarray(w_pred).ravel()
#     w_ref = np.asarray(w_ref).ravel()
#     r2 = r2_score(w_pred, w_ref)
#     fig, ax = plt.subplots(figsize=(4.8, 4.6))
#     ax.scatter(w_ref, w_pred, s=5, alpha=0.4, color="#d62728")
#     lo, hi = min(w_ref.min(), w_pred.min()), max(w_ref.max(), w_pred.max())
#     ax.plot([lo, hi], [lo, hi], "k--", lw=1)
#     ax.set_xlabel("w referencia"); ax.set_ylabel(f"w {label}")
#     ax.set_title(f"{label}  (R2 = {r2:.4f})"); ax.set_aspect("equal")
#     return _save(fig, save), fig
# 
# 
# # --------------------------------------------------------------------------
# # Comparacao final (figuras 14-19)
# # --------------------------------------------------------------------------
# 
# def fig_panel_w(sols: dict, case, save="14_painel_w.png"):
#     """Fig 14: painel lado a lado de w por metodo, MESMA escala de cor."""
#     names = list(sols.keys())
#     vmin = min(s["W"].min() for s in sols.values())
#     vmax = max(s["W"].max() for s in sols.values())
#     fig, axes = plt.subplots(1, len(names), figsize=(4.6 * len(names), 4.2))
#     if len(names) == 1:
#         axes = [axes]
#     for ax, name in zip(axes, names):
#         s = sols[name]
#         pc = ax.pcolormesh(s["X"], s["Y"], s["W"], cmap=W_CMAP, shading="auto",
#                            vmin=vmin, vmax=vmax)
#         overlay_inclusion(ax, case)
#         ax.set_title(f"w - {name}"); ax.set_aspect("equal")
#         ax.set_xlabel("x"); ax.set_ylabel("y")
#     fig.colorbar(pc, ax=axes, label="w", fraction=0.046, pad=0.04)
#     return _save(fig, save), fig
#
#
# def fig_panel_contourf(sols: dict, case, field="W", save="14b_painel_curvas.png",
#                        levels=18, cmap=None):
#     """Painel comparativo dos tres metodos como heatmap 'em curvas' (contourf).
#
#     Todos os subplots compartilham os MESMOS niveis (mesma escala de cor e as
#     mesmas isolinhas), para que a comparacao MDF x MEF x PINN seja justa.
#     """
#     names = list(sols.keys())
#     cmap = cmap or (W_CMAP if field == "W" else TAU_CMAP)
#     vmin = min(s[field].min() for s in sols.values())
#     vmax = max(s[field].max() for s in sols.values())
#     lv = np.linspace(vmin, vmax, levels + 1)
#     fig, axes = plt.subplots(1, len(names), figsize=(4.6 * len(names), 4.2))
#     if len(names) == 1:
#         axes = [axes]
#     cf = None
#     for ax, name in zip(axes, names):
#         s = sols[name]
#         cf = ax.contourf(s["X"], s["Y"], s[field], levels=lv, cmap=cmap,
#                          extend="both")
#         ax.contour(s["X"], s["Y"], s[field], levels=lv, colors="k",
#                    linewidths=0.35, alpha=0.4)
#         overlay_inclusion(ax, case)
#         ax.set_title(f"{field} - {name}"); ax.set_aspect("equal")
#         ax.set_xlabel("x"); ax.set_ylabel("y")
#     fig.colorbar(cf, ax=axes, label=field, fraction=0.046, pad=0.04)
#     return _save(fig, save), fig
#
#
# def fig_panel_diff(sols: dict, case, save="15_painel_diferencas.png"):
#     """Fig 15: painel de diferencas entre pares de metodos."""
#     names = list(sols.keys())
#     pairs = [(names[i], names[j]) for i in range(len(names)) for j in range(i + 1, len(names))]
#     fig, axes = plt.subplots(1, len(pairs), figsize=(4.6 * len(pairs), 4.2))
#     if len(pairs) == 1:
#         axes = [axes]
#     for ax, (a, b) in zip(axes, pairs):
#         d = sols[a]["W"] - sols[b]["W"]
#         lim = np.abs(d).max() or 1e-12
#         pc = ax.pcolormesh(sols[a]["X"], sols[a]["Y"], d, cmap=DIFF_CMAP,
#                            shading="auto", vmin=-lim, vmax=lim)
#         overlay_inclusion(ax, case)
#         ax.set_title(f"{a} - {b}"); ax.set_aspect("equal")
#         ax.set_xlabel("x"); ax.set_ylabel("y")
#         fig.colorbar(pc, ax=ax, fraction=0.046, pad=0.04)
#     return _save(fig, save), fig
# 
# 
# def fig_centerline_methods(sols: dict, case, field="W", save="16_perfis_central.png"):
#     """Fig 16: perfis na linha central, varios metodos sobrepostos."""
#     fig, ax = plt.subplots(figsize=(6.4, 4.2))
#     for name, s in sols.items():
#         n = s[field].shape[1]
#         jmid = n // 2
#         ax.plot(s["X"][:, jmid], s[field][:, jmid], label=name,
#                 color=METHOD_COLORS.get(name), lw=1.8)
#     ax.axvspan(case.center[0] - case.a, case.center[0] + case.a,
#                color="0.85", alpha=0.5)
#     ax.set_xlabel("x"); ax.set_ylabel(f"{field} (linha central)")
#     ax.set_title(f"Perfil central de {field}"); ax.legend(fontsize=8); ax.grid(alpha=0.3)
#     return _save(fig, save), fig
# 
# 
# def fig_convergence(Ns, errs, save="17_convergencia.png"):
#     """Fig 17: estudo de convergencia e_rel vs N (log-log)."""
#     fig, ax = plt.subplots(figsize=(5.6, 4.2))
#     ax.loglog(Ns, errs, "o-", color="#1f77b4")
#     # linha de referencia de ordem 2
#     Ns = np.asarray(Ns, float)
#     ref = errs[0] * (Ns[0] / Ns) ** 2
#     ax.loglog(Ns, ref, "k--", lw=1, label="ordem 2 (ref.)")
#     ax.set_xlabel("N"); ax.set_ylabel("e_rel (w)")
#     ax.set_title("Convergencia MDF"); ax.legend(fontsize=8); ax.grid(alpha=0.3, which="both")
#     return _save(fig, save), fig
# 
# 
# def fig_contrast_study(ratios, gefs, tau_peaks, save="18_contraste.png"):
#     """Fig 18: Gef e pico de tau na interface vs razao Gi/Gm."""
#     fig, ax1 = plt.subplots(figsize=(6.2, 4.2))
#     ax1.semilogx(ratios, gefs, "o-", color="#1f77b4", label="Gef")
#     ax1.set_xlabel("Gi/Gm"); ax1.set_ylabel("Gef", color="#1f77b4")
#     ax2 = ax1.twinx()
#     ax2.semilogx(ratios, tau_peaks, "s--", color="#d62728", label="pico |tau|")
#     ax2.set_ylabel("pico |tau|", color="#d62728")
#     ax1.set_title("Estudo de contraste Gi/Gm"); ax1.grid(alpha=0.3, which="both")
#     return _save(fig, save), fig
# 
# 
# def fig_error_bars(err_table: dict, save="19_barras_erro.png"):
#     """Fig 19: barras dos erros relativos finais (w, txz, tyz) por metodo.
# 
#     err_table: {metodo: {'w':..,'txz':..,'tyz':..}}
#     """
#     methods = list(err_table.keys())
#     fields = ["w", "txz", "tyz"]
#     x = np.arange(len(fields))
#     width = 0.8 / max(len(methods), 1)
#     fig, ax = plt.subplots(figsize=(6.4, 4.2))
#     for k, m in enumerate(methods):
#         vals = [err_table[m][f] for f in fields]
#         ax.bar(x + k * width, vals, width, label=m, color=METHOD_COLORS.get(m))
#     ax.set_xticks(x + width * (len(methods) - 1) / 2)
#     ax.set_xticklabels(fields)
#     ax.set_ylabel("erro relativo L2"); ax.set_yscale("log")
#     ax.set_title("Erros relativos por metodo"); ax.legend(fontsize=8)
#     return _save(fig, save), fig
# 
# 
# def all_fields_for_method(sol, name, case, prefix):
#     """Conveniencia: gera as figuras de campo (5-9) para um metodo, prefixadas."""
#     paths = []
#     paths.append(fig_field_heatmap(sol, "W", case, f"{prefix}_05_w_heatmap.png",
#                                    title=f"w(x,y) - {name}")[0])
#     paths.append(fig_surface(sol, case, f"{prefix}_06_w_superficie.png",
#                              title=f"w(x,y) - {name}")[0])
#     paths.append(fig_contour(sol, case, f"{prefix}_07_w_contorno.png",
#                              title=f"Curvas de nivel - {name}")[0])
#     paths.append(fig_field_heatmap(sol, "txz", case, f"{prefix}_08a_txz.png",
#                                    title=f"txz - {name}")[0])
#     paths.append(fig_field_heatmap(sol, "tyz", case, f"{prefix}_08b_tyz.png",
#                                    title=f"tyz - {name}")[0])
#     paths.append(fig_flux_field(sol, case, f"{prefix}_09_fluxo.png")[0])
#     plt.close("all")
#     return paths
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/pinn.py
# """Physics-Informed Neural Network (PINN) para o cisalhamento antiplano.
# 
# Estrategia PRINCIPAL: dominio decomposto (secao 5.3 do CLAUDE.md).
#   Como G e constante em cada fase, a EDP -div(G grad w)=0 vira a equacao de
#   Laplace  lap(w)=0  dentro de cada subdominio; toda a fisica nao-trivial fica
#   na interface. Usamos duas redes:
#       net_m -> w na matriz (Omega_m)
#       net_i -> w na inclusao (Omega_i)
#   Loss = L_EDP + L_CC + L_I
#       L_EDP : residuo de Laplace em pontos de colocacao de cada subdominio.
#       L_CC  : Dirichlet (x=0, x=L) + Neumann homogeneo (y=0, y=L), so na matriz.
#       L_I   : na interface,  wm = wi  e  Gm dwm/dn = Gi dwi/dn.
# 
# Estrategia SECUNDARIA (para o relatorio): PINN unica sobre G(x,y) descontinuo,
# para evidenciar a dificuldade perto da interface. Ver `train_single_pinn`.
# 
# Framework: PyTorch; derivadas via torch.autograd.grad.
# """
# 
# import numpy as np
# import torch
# import torch.nn as nn
# 
# from .geometry import Case, inclusion_mask
# 
# 
# def set_seed(seed=42):
#     torch.manual_seed(seed)
#     np.random.seed(seed)
# 
# 
# class MLP(nn.Module):
#     """MLP simples com ativacao tanh. Normaliza a entrada de [0,L]^2 p/ [-1,1]^2."""
# 
#     def __init__(self, L=1.0, hidden=48, layers=5):
#         super().__init__()
#         self.L = L
#         acts = []
#         dims = [2] + [hidden] * layers + [1]
#         mods = []
#         for k in range(len(dims) - 1):
#             mods.append(nn.Linear(dims[k], dims[k + 1]))
#             if k < len(dims) - 2:
#                 mods.append(nn.Tanh())
#         self.net = nn.Sequential(*mods)
# 
#     def forward(self, xy):
#         z = 2.0 * xy / self.L - 1.0  # normaliza p/ [-1,1]
#         return self.net(z)
# 
# 
# def _grad(out, inp):
#     """d(out)/d(inp), mantendo o grafo para derivadas de ordem superior."""
#     return torch.autograd.grad(out, inp, grad_outputs=torch.ones_like(out),
#                                create_graph=True)[0]
# 
# 
# def _laplacian(w, xy):
#     """Laplaciano de w em xy=(x,y) via autograd (segunda derivada)."""
#     g = _grad(w, xy)
#     wx, wy = g[:, 0:1], g[:, 1:2]
#     wxx = _grad(wx, xy)[:, 0:1]
#     wyy = _grad(wy, xy)[:, 1:2]
#     return wxx + wyy
# 
# 
# # --------------------------------------------------------------------------
# # Amostragem de pontos de colocacao
# # --------------------------------------------------------------------------
# 
# def sample_points(case: Case, n_dom=4000, n_bc=400, n_iface=600, seed=0):
#     """Gera pontos de colocacao para o caso (inclusao quadrada).
# 
#     Retorna dict de arrays numpy (n,2):
#       interior_m, interior_i, bc_left, bc_right, bc_top, bc_bot, interface
#     """
#     rng = np.random.default_rng(seed)
#     L, a = case.L, case.a
#     cx, cy = case.center
# 
#     # Interior: amostra uniforme e separa por fase
#     P = rng.uniform(0, L, size=(int(n_dom * 1.6), 2))
#     inside = inclusion_mask(P[:, 0], P[:, 1], case)
#     interior_i = P[inside][:n_dom]
#     interior_m = P[~inside][:n_dom]
# 
#     # Contornos externos
#     s = rng.uniform(0, L, size=(n_bc, 1))
#     bc_left = np.column_stack([np.zeros_like(s), s])
#     bc_right = np.column_stack([np.full_like(s, L), s])
#     bc_bot = np.column_stack([s, np.zeros_like(s)])
#     bc_top = np.column_stack([s, np.full_like(s, L)])
# 
#     # Interface: depende da forma da inclusao.
#     if case.shape == "square":
#         # quadrado |x-cx|=a ou |y-cy|=a; amostra os 4 lados.
#         t = rng.uniform(-a, a, size=(n_iface // 4, 1))
#         left = np.column_stack([np.full_like(t, cx - a), cy + t])
#         right = np.column_stack([np.full_like(t, cx + a), cy + t])
#         bot = np.column_stack([cx + t, np.full_like(t, cy - a)])
#         top = np.column_stack([cx + t, np.full_like(t, cy + a)])
#         interface = np.vstack([left, right, bot, top])
#     else:
#         # circulo r=a centrado em (cx,cy)
#         th = rng.uniform(0, 2 * np.pi, size=(n_iface, 1))
#         interface = np.column_stack([cx + a * np.cos(th), cy + a * np.sin(th)])
# 
#     return dict(interior_m=interior_m, interior_i=interior_i,
#                 bc_left=bc_left, bc_right=bc_right, bc_top=bc_top, bc_bot=bc_bot,
#                 interface=interface)
# 
# 
# def _interface_normals(case: Case, pts):
#     """Normais externas (apontando da inclusao p/ a matriz) nos pontos da interface."""
#     cx, cy = case.center
#     a = case.a
#     dx = pts[:, 0] - cx
#     dy = pts[:, 1] - cy
#     n = np.zeros_like(pts)
#     if case.shape == "square":
#         # ponto pertence a face vertical se |dx| ~ a, senao horizontal
#         vert = np.abs(np.abs(dx) - a) <= np.abs(np.abs(dy) - a)
#         n[vert, 0] = np.sign(dx[vert])
#         n[~vert, 1] = np.sign(dy[~vert])
#     else:
#         # circulo: normal radial unitaria
#         r = np.hypot(dx, dy)
#         r = np.where(r == 0.0, 1.0, r)
#         n[:, 0] = dx / r
#         n[:, 1] = dy / r
#     return n
# 
# 
# # --------------------------------------------------------------------------
# # Treino: PINN com dominio decomposto
# # --------------------------------------------------------------------------
# 
# def train_decomposed(case: Case, epochs=4000, lr=1e-3, hidden=48, layers=5,
#                      weights=None, seed=42, device="cpu", verbose=True,
#                      points=None):
#     """Treina as duas redes acopladas. Retorna (net_m, net_i, history, points)."""
#     set_seed(seed)
#     weights = weights or dict(edp=1.0, bc=10.0, iface=10.0)
#     pts = points or sample_points(case, seed=seed)
# 
#     def T(arr, grad=False):
#         t = torch.tensor(arr, dtype=torch.float32, device=device)
#         t.requires_grad_(grad)
#         return t
# 
#     Xm = T(pts["interior_m"], grad=True)
#     Xi = T(pts["interior_i"], grad=True)
#     Xl = T(pts["bc_left"]); Xr = T(pts["bc_right"])
#     Xt = T(pts["bc_top"], grad=True); Xb = T(pts["bc_bot"], grad=True)
#     Xf = T(pts["interface"], grad=True)
#     nrm = T(_interface_normals(case, pts["interface"]))
# 
#     net_m = MLP(case.L, hidden, layers).to(device)
#     net_i = MLP(case.L, hidden, layers).to(device)
#     opt = torch.optim.Adam(list(net_m.parameters()) + list(net_i.parameters()), lr=lr)
# 
#     history = dict(total=[], edp=[], bc=[], iface=[])
#     mse = nn.MSELoss()
# 
#     for ep in range(epochs):
#         opt.zero_grad()
# 
#         # L_EDP: Laplace em cada subdominio
#         lap_m = _laplacian(net_m(Xm), Xm)
#         lap_i = _laplacian(net_i(Xi), Xi)
#         L_edp = mse(lap_m, torch.zeros_like(lap_m)) + mse(lap_i, torch.zeros_like(lap_i))
# 
#         # L_CC: Dirichlet laterais + Neumann topo/base (so a matriz toca o externo)
#         wl = net_m(Xl); wr = net_m(Xr)
#         L_dir = mse(wl, torch.zeros_like(wl)) + \
#             mse(wr, torch.full_like(wr, case.gamma * case.L))
#         wt = net_m(Xt); wb = net_m(Xb)
#         dwt = _grad(wt, Xt)[:, 1:2]   # dw/dy no topo
#         dwb = _grad(wb, Xb)[:, 1:2]   # dw/dy na base
#         L_neu = mse(dwt, torch.zeros_like(dwt)) + mse(dwb, torch.zeros_like(dwb))
#         L_cc = L_dir + L_neu
# 
#         # L_I: continuidade + equilibrio de fluxo na interface
#         wm_f = net_m(Xf); wi_f = net_i(Xf)
#         L_cont = mse(wm_f, wi_f)
#         gm = _grad(wm_f, Xf); gi = _grad(wi_f, Xf)
#         dwm_n = (gm * nrm).sum(dim=1, keepdim=True)   # dwm/dn
#         dwi_n = (gi * nrm).sum(dim=1, keepdim=True)   # dwi/dn
#         L_flux = mse(case.Gm * dwm_n, case.Gi * dwi_n)
#         L_iface = L_cont + L_flux
# 
#         loss = weights["edp"] * L_edp + weights["bc"] * L_cc + weights["iface"] * L_iface
#         loss.backward()
#         opt.step()
# 
#         history["total"].append(loss.item())
#         history["edp"].append(L_edp.item())
#         history["bc"].append(L_cc.item())
#         history["iface"].append(L_iface.item())
#         if verbose and (ep % max(1, epochs // 10) == 0 or ep == epochs - 1):
#             print(f"  ep {ep:5d}  loss={loss.item():.3e}  edp={L_edp.item():.2e} "
#                   f"bc={L_cc.item():.2e} iface={L_iface.item():.2e}")
# 
#     return net_m, net_i, history, pts
# 
# 
# def evaluate_decomposed(net_m, net_i, case: Case, N=80, device="cpu"):
#     """Avalia as redes numa malha (N+1)x(N+1) e retorna dict no formato dos solvers."""
#     from .geometry import grid, G_field
#     X, Y, x1d, h = grid(N, case)
#     pts = np.column_stack([X.ravel(), Y.ravel()])
#     inside = inclusion_mask(pts[:, 0], pts[:, 1], case)
# 
#     net_m.eval(); net_i.eval()
#     xy = torch.tensor(pts, dtype=torch.float32, device=device, requires_grad=True)
#     # Deslocamento (costurado por fase)
#     wm = net_m(xy); wi = net_i(xy)
#     gm = _grad(wm, xy).detach().cpu().numpy()
#     gi = _grad(wi, xy).detach().cpu().numpy()
#     wm_np = wm.detach().cpu().numpy().ravel()
#     wi_np = wi.detach().cpu().numpy().ravel()
#     W = np.where(inside, wi_np, wm_np).reshape(X.shape)
# 
#     # Tensoes via autograd EM CADA SUBDOMINIO (gradiente exato da rede, sem o
#     # artefato de diferenciar o campo costurado atraves da interface).
#     G = np.where(inside, case.Gi, case.Gm)
#     dwdx = np.where(inside, gi[:, 0], gm[:, 0])
#     dwdy = np.where(inside, gi[:, 1], gm[:, 1])
#     txz = (G * dwdx).reshape(X.shape)
#     tyz = (G * dwdy).reshape(X.shape)
#     Gef = float(np.mean(txz) / case.gamma)
#     return dict(X=X, Y=Y, W=W, txz=txz, tyz=tyz, Gef=Gef, h=h, N=N, case=case)
# 
# 
# # --------------------------------------------------------------------------
# # Estrategia secundaria: PINN unica sobre G descontinuo
# # --------------------------------------------------------------------------
# 
# def train_single_pinn(case: Case, epochs=4000, lr=1e-3, hidden=48, layers=5,
#                       seed=42, device="cpu", verbose=True):
#     """PINN unica resolvendo a forma fraca/forte com G descontinuo.
# 
#     Usa a forma  div(G grad w) = 0  diretamente. Como G e descontinuo, a rede
#     tem dificuldade na interface -- exatamente o ponto que queremos evidenciar.
#     Retorna (net, history).
#     """
#     set_seed(seed)
#     pts = sample_points(case, seed=seed)
#     rng = np.random.default_rng(seed)
#     # mistura interior das duas fases num unico conjunto
#     Xall = np.vstack([pts["interior_m"], pts["interior_i"]])
#     rng.shuffle(Xall)
# 
#     def T(arr, grad=False):
#         t = torch.tensor(arr, dtype=torch.float32, device=device)
#         t.requires_grad_(grad)
#         return t
# 
#     Xd = T(Xall, grad=True)
#     Gd = torch.tensor(
#         np.where(inclusion_mask(Xall[:, 0], Xall[:, 1], case), case.Gi, case.Gm),
#         dtype=torch.float32, device=device).reshape(-1, 1)
#     Xl = T(pts["bc_left"]); Xr = T(pts["bc_right"])
#     Xt = T(pts["bc_top"], grad=True); Xb = T(pts["bc_bot"], grad=True)
# 
#     net = MLP(case.L, hidden, layers).to(device)
#     opt = torch.optim.Adam(net.parameters(), lr=lr)
#     mse = nn.MSELoss()
#     history = dict(total=[], edp=[], bc=[])
# 
#     for ep in range(epochs):
#         opt.zero_grad()
#         w = net(Xd)
#         g = _grad(w, Xd)
#         # residuo de div(G grad w); G localmente constante -> G * lap(w)
#         lap = _laplacian(w, Xd)
#         res = Gd * lap
#         L_edp = mse(res, torch.zeros_like(res))
# 
#         wl = net(Xl); wr = net(Xr)
#         L_dir = mse(wl, torch.zeros_like(wl)) + \
#             mse(wr, torch.full_like(wr, case.gamma * case.L))
#         wt = net(Xt); wb = net(Xb)
#         L_neu = mse(_grad(wt, Xt)[:, 1:2], torch.zeros((Xt.shape[0], 1), device=device)) + \
#             mse(_grad(wb, Xb)[:, 1:2], torch.zeros((Xb.shape[0], 1), device=device))
#         L_bc = L_dir + L_neu
# 
#         loss = L_edp + 10.0 * L_bc
#         loss.backward(); opt.step()
#         history["total"].append(loss.item())
#         history["edp"].append(L_edp.item())
#         history["bc"].append(L_bc.item())
#         if verbose and (ep % max(1, epochs // 10) == 0 or ep == epochs - 1):
#             print(f"  [single] ep {ep:5d}  loss={loss.item():.3e}")
#     return net, history
# 
# 
# def evaluate_single(net, case: Case, N=80, device="cpu"):
#     from .geometry import grid, G_field
#     X, Y, x1d, h = grid(N, case)
#     xy = torch.tensor(np.column_stack([X.ravel(), Y.ravel()]),
#                       dtype=torch.float32, device=device)
#     net.eval()
#     with torch.no_grad():
#         W = net(xy).cpu().numpy().reshape(X.shape)
#     Gnod = G_field(X, Y, case)
#     txz = Gnod * np.gradient(W, h, axis=0)
#     tyz = Gnod * np.gradient(W, h, axis=1)
#     Gef = float(np.mean(txz) / case.gamma)
#     return dict(X=X, Y=Y, W=W, txz=txz, tyz=tyz, Gef=Gef, h=h, N=N, case=case)
#

# Confirma que tudo importa
from src.geometry import OFFICIAL, VALIDATION, Case
print('Módulos OK. Caso oficial:', OFFICIAL)

"""## 1. Preparação e o problema físico

Uma **célula quadrada** $\Omega=[0,L]^2$ com uma **inclusão quadrada central** de
módulo de cisalhamento $G_i$ diferente da matriz $G_m$. No **cisalhamento antiplano**
a incógnita é o deslocamento fora do plano $w(x,y)$:

$$-\nabla\cdot\big(G(x,y)\,\nabla w\big)=0,\qquad
w(0,y)=0,\ w(L,y)=\gamma L,\ \partial_y w|_{y=0,L}=0.$$

Na interface: $w_m=w_i$ (continuidade) e $G_m\partial_n w_m=G_i\partial_n w_i$
(equilíbrio do fluxo). Tensões $\tau_{xz}=G\partial_x w$, $\tau_{yz}=G\partial_y w$;
módulo efetivo $G_{ef}=\langle\tau_{xz}\rangle/\gamma$. Parâmetros oficiais:
$L=1,\ a=0.15,\ G_m=1,\ G_i=5,\ \gamma=0.01$.

"""

import numpy as np, torch
from IPython.display import Image, display

from src.analytic import w_analytic, tau_analytic
from src.fdm import solve_fdm
from src.fem import solve_fem
from src.metrics import field_errors, rel_l2, r2_score
from src import viz, pinn

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
print('torch', torch.__version__, '| device =', DEVICE)

FIG = os.path.join('outputs', 'figures')
def show(name, w=560):
    "Exibe uma figura salva em outputs/figures/."
    display(Image(filename=os.path.join(FIG, name), width=w))

viz.fig_material_map(OFFICIAL, save='nb_material.png')
show('nb_material.png')

"""## 2. Validação contra a solução analítica (inclusão circular)

O caso quadrado não tem solução fechada, mas a **inclusão circular** em matriz
infinita tem. Validamos o solver comparando o perfil de $w$ na linha central
(longe das bordas, pois a teoria supõe matriz infinita). Caso: $G_i=10$.

"""

cval = VALIDATION
sol_val = solve_fdm(cval, N=120)
X, Y = sol_val['X'], sol_val['Y']
mask = (X > 0.2) & (X < 0.8) & (Y > 0.2) & (Y < 0.8)
print(f'MDF vs analítico: erro relativo L2 no interior = {rel_l2(sol_val["W"], w_analytic(X,Y,cval), mask):.3%}')

viz.fig_centerline_validation(sol_val, w_analytic, cval, save='nb_val_perfil.png')
viz.fig_error_map(sol_val, w_analytic, cval, save='nb_val_erro.png')
show('nb_val_perfil.png'); show('nb_val_erro.png')

"""## 3. Método de Diferenças Finitas (MDF)

Malha regular $(N{+}1)^2$, forma **conservativa** com **média harmônica de $G$ nas
faces** — é o que trata corretamente o salto de $G$ na interface (continuidade do
fluxo). Neumann por nós-fantasma, Dirichlet por linha identidade. Resolve sistema
linear esparso.

"""

sol_fdm = solve_fdm(OFFICIAL, N=80)
print(f"MDF: Gef = {sol_fdm['Gef']:.4f}")
viz.fig_field_heatmap(sol_fdm, 'W', OFFICIAL, save='nb_fdm_w.png', title='w(x,y) — MDF')
viz.fig_field_heatmap(sol_fdm, 'txz', OFFICIAL, save='nb_fdm_txz.png', title='τxz — MDF')
viz.fig_flux_field(sol_fdm, OFFICIAL, save='nb_fdm_fluxo.png')
show('nb_fdm_w.png'); show('nb_fdm_txz.png'); show('nb_fdm_fluxo.png')

"""A inclusão mais rígida ($G_i=5$) concentra tensão (picos nos cantos) e achata
o gradiente de $w$ — fisicamente correto.

## 4. Método de Elementos Finitos (MEF)

Forma fraca $\int_\Omega G\nabla w\cdot\nabla v=0$, **elementos Q4** bilineares,
$G$ por elemento (centroide), **Gauss 2×2**. Neumann é condição natural; Dirichlet
por eliminação. Escrito na mão.
"""

sol_fem = solve_fem(OFFICIAL, N=80)
print(f"MEF: Gef = {sol_fem['Gef']:.4f}")
viz.fig_fem_mesh(OFFICIAL, N=24, save='nb_fem_malha.png')
viz.fig_field_heatmap(sol_fem, 'W', OFFICIAL, save='nb_fem_w.png', title='w(x,y) — MEF')
show('nb_fem_malha.png'); show('nb_fem_w.png')

"""## 5. PINN — Physics-Informed Neural Network  ⭐ (parte central)

### 5.1 O que é
Em vez de malha + sistema linear, uma **rede neural** $\mathcal{N}_\theta(x,y)\approx w$
ajusta seus pesos para **obedecer à física**. Não há dados: a supervisão é a própria
EDP. As derivadas saem por **diferenciação automática** (`torch.autograd`), exatas.

### 5.2 Por que *domínio decomposto*
$G$ é descontínuo na interface. Como $G$ é **constante em cada fase**, a EDP vira
$\nabla^2 w=0$ (Laplace) dentro de cada subdomínio, e toda a física fica **na
interface**. Usamos **duas redes**: $\mathcal{N}_m$ (matriz) e $\mathcal{N}_i$
(inclusão), acopladas na interface.

### 5.3 A *loss*
$$\mathcal{L}=\mathcal{L}_{EDP}+\lambda_{cc}\mathcal{L}_{CC}+\lambda_{I}\mathcal{L}_{I}$$
- $\mathcal{L}_{EDP}$: resíduo de Laplace $(\nabla^2 w)^2$ dentro de cada subdomínio;
- $\mathcal{L}_{CC}$: Dirichlet laterais + Neumann topo/base (só a matriz toca a borda);
- $\mathcal{L}_{I}$: na interface, $w_m=w_i$ **e** $G_m\partial_n w_m=G_i\partial_n w_i$.

### 5.4 Arquitetura
MLP 5×48, tanh, entrada $(x,y)$ normalizada, Adam, `seed` fixa, $\lambda_{cc}=\lambda_I=10$.

Abaixo treinamos a PINN **aqui no Colab** (≈1–2 min em CPU). Primeiro, os pontos de
colocação:

"""

pts = pinn.sample_points(OFFICIAL, seed=42)
viz.fig_pinn_points(pts, OFFICIAL, save='nb_pinn_pts.png')
show('nb_pinn_pts.png')

"""**Treino da PINN decomposta** (ajuste `EPOCHS` se quiser; 4000 é um bom padrão):"""

EPOCHS = 4000
net_m, net_i, history, _ = pinn.train_decomposed(
    OFFICIAL, epochs=EPOCHS, device=DEVICE, points=pts, verbose=True)

sol_pinn = pinn.evaluate_decomposed(net_m, net_i, OFFICIAL, N=80, device=DEVICE)
print(f"\nPINN: Gef = {sol_pinn['Gef']:.4f}")
err = field_errors(sol_pinn, sol_fdm)   # referência = MDF
print(f"Erro vs MDF:  w={err['w']:.2%}  τxz={err['txz']:.2%}  τyz={err['tyz']:.2%}")

# Evolução da loss e qualidade do ajuste
viz.fig_loss_history(history, save='nb_pinn_loss.png')
viz.fig_field_heatmap(sol_pinn, 'W', OFFICIAL, save='nb_pinn_w.png', title='w(x,y) — PINN')
viz.fig_scatter_r2(sol_pinn['W'], sol_fdm['W'], save='nb_pinn_scatter.png', label='PINN')
show('nb_pinn_loss.png'); show('nb_pinn_w.png'); show('nb_pinn_scatter.png')

"""### 5.5 Detalhe técnico (tensões da PINN)
As tensões **não** vêm de diferença finita sobre o campo "costurado" das duas redes
(isso criaria gradientes espúrios na interface). Usamos o **gradiente exato de cada
rede no seu subdomínio** (autograd) e selecionamos por fase.

### 5.6 PINN única (secundária)
Há também `pinn.train_single_pinn`, uma rede só sobre o $G$ descontínuo, para
evidenciar a dificuldade na interface. A decomposta é a principal.

## 6. Comparação final dos três métodos
"""

sols = {'MDF': sol_fdm, 'MEF': sol_fem, 'PINN': sol_pinn}
viz.fig_panel_w(sols, OFFICIAL, save='nb_cmp_painel.png')
viz.fig_centerline_methods(sols, OFFICIAL, field='W', save='nb_cmp_perfil_w.png')
viz.fig_centerline_methods(sols, OFFICIAL, field='txz', save='nb_cmp_perfil_txz.png')
show('nb_cmp_painel.png'); show('nb_cmp_perfil_w.png'); show('nb_cmp_perfil_txz.png')

"""### 6.1 Gráficos de calor "em curvas" (isolinhas preenchidas)

O mesmo campo $w(x,y)$ visto como **gráfico de calor em curvas**: bandas de cor
(`contourf`) com as **linhas de nível** sobrepostas — realçam por onde o campo
cresce. Primeiro cada método isolado; depois **os três lado a lado** (mesma escala
e mesmos níveis) como comparativo.
"""

# Um heatmap "em curvas" por método
viz.fig_field_contourf(sol_fdm,  'W', OFFICIAL, save='nb_curvas_mdf.png',  title='w(x,y) — MDF (curvas)')
viz.fig_field_contourf(sol_fem,  'W', OFFICIAL, save='nb_curvas_mef.png',  title='w(x,y) — MEF (curvas)')
viz.fig_field_contourf(sol_pinn, 'W', OFFICIAL, save='nb_curvas_pinn.png', title='w(x,y) — PINN (curvas)')
show('nb_curvas_mdf.png'); show('nb_curvas_mef.png'); show('nb_curvas_pinn.png')

# Comparativo dos três métodos no mesmo gráfico de calor em curvas
viz.fig_panel_contourf(sols, OFFICIAL, field='W', save='nb_curvas_comparativo.png')
show('nb_curvas_comparativo.png')

# Tabela de erros (referência = MDF)
rows = {'MEF': field_errors(sol_fem, sol_fdm), 'PINN': field_errors(sol_pinn, sol_fdm)}
print('Erro relativo L2 (vs MDF):')
print(f"{'método':8s} {'w':>10s} {'txz':>10s} {'tyz':>10s}")
for m, e in rows.items():
    print(f"{m:8s} {e['w']:10.3e} {e['txz']:10.3e} {e['tyz']:10.3e}")
viz.fig_error_bars(rows, save='nb_cmp_barras.png')
show('nb_cmp_barras.png')

"""**Estudo de convergência** do MDF (erro vs $N$, log-log) e **estudo de
contraste** ($G_{ef}$ e pico de tensão vs razão $G_i/G_m$):
"""

# Convergência do MDF contra a analítica circular
Ns, errs = [20, 40, 80, 160], []
for N in Ns:
    s = solve_fdm(VALIDATION, N=N); Xv, Yv = s['X'], s['Y']
    m = (Xv>0.2)&(Xv<0.8)&(Yv>0.2)&(Yv<0.8)
    errs.append(rel_l2(s['W'], w_analytic(Xv,Yv,VALIDATION), m))
viz.fig_convergence(Ns, np.array(errs), save='nb_cmp_conv.png')

# Contraste Gi/Gm
ratios, gefs, peaks = [1,2,5,10,50,100], [], []
for r in ratios:
    s = solve_fdm(Case(L=1,a=0.15,Gm=1,Gi=float(r),gamma=0.01,shape='square'), N=80)
    gefs.append(s['Gef']); peaks.append(float(np.hypot(s['txz'],s['tyz']).max()))
viz.fig_contrast_study(ratios, gefs, peaks, save='nb_cmp_contraste.png')
show('nb_cmp_conv.png'); show('nb_cmp_contraste.png')

"""## 7. Conclusões

- **MDF e MEF concordam** quase exatamente (mesmo $G_{ef}\approx1.14$) → confiança na
  solução de referência. A média harmônica (MDF) e o $G$ por elemento (MEF) tratam bem
  o salto material.
- A **PINN decomposta** captura bem $w$ (erro de poucos %), mas é **menos precisa**
  que MDF/MEF, sobretudo nas **tensões** e **junto à interface** — comportamento
  esperado e o motivo de decompor o domínio. É a mais flexível (sem malha) e a mais
  difícil de treinar.

*Notebook autocontido — todo o código está nas células `%%writefile src/...` no topo.*

"""